spring.application.name=PharmacyManagement

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url= jdbc:mysql://localhost:3306/pharmacy
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8085

#Image Configuration
#image.upload.dir=F:/JEE/Spring/assets
image.upload.dir=D:/SpringBoot-Project-Using-Angular/assets
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mishkatulkazi
spring.mail.password=lvec qhyh bdrc hqoq
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


jwt.secret=74b6136ff863737d44afb8d5e7abef843cmishkat84a974a9b0f4bd3b9836be4
jwt.expiration=86400000

jwt.verification-expiration=3600000
jwt.reset-expiration=900000
#1 day = 24 hours = 86,400,000 ms
#1 hour = 3,600,000 ms
#15 minutes = 900,000 ms

spring.security.user.name=admin
spring.security.user.password=1234

app.frontend-url= http://localhost:4200